"""Guards that keep the generated reference honest.

`docs/reference.md` is generated by `scripts/gen_docs.py` from the vocab, CLI,
and HTTP route tables. These tests fail if (a) the committed reference is stale,
or (b) the documented `ROUTES` table drifts from the server's actual dispatch.
"""

from __future__ import annotations

import importlib.util
import inspect
import re
from pathlib import Path

import timbre.server as server

REPO_ROOT = Path(__file__).resolve().parent.parent


def _load_gen_docs():
    path = REPO_ROOT / "scripts" / "gen_docs.py"
    spec = importlib.util.spec_from_file_location("gen_docs", path)
    module = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    spec.loader.exec_module(module)
    return module


def test_reference_md_is_up_to_date():
    gen = _load_gen_docs()
    expected = gen.render()
    out = REPO_ROOT / "docs" / "reference.md"
    assert out.exists(), "docs/reference.md is missing — run: python scripts/gen_docs.py"
    assert out.read_text() == expected, (
        "docs/reference.md is stale — run: python scripts/gen_docs.py"
    )


def _dispatched_paths() -> set[str]:
    """Path string literals compared in the server's do_* dispatch methods."""
    # The dispatch lives on the request-handler class; scan its source.
    src = inspect.getsource(server)
    do_blocks = re.findall(r"def do_(?:GET|POST|DELETE)\b.*?(?=\n    def |\nclass |\Z)",
                           src, re.DOTALL)
    paths: set[str] = set()
    for block in do_blocks:
        # parsed.path == "/x"  |  path == "/x"  |  path in ("/", "/ui", ...)
        for m in re.findall(r'==\s*"(/[^"]*)"', block):
            paths.add(m)
        for grp in re.findall(r'\bin\s*\(([^)]*)\)', block):
            paths.update(re.findall(r'"(/[^"]*)"', grp))
    return paths


def test_routes_table_matches_dispatch():
    documented = {path.split("?")[0] for _, path, _ in server.ROUTES}
    dispatched = _dispatched_paths()

    # Every documented route must actually be dispatched. "/" stands in for the
    # UI aliases (/ui, /index.html), which are documented in the same row.
    ui_aliases = {"/ui", "/index.html"}
    missing = documented - dispatched
    assert not missing, f"ROUTES documents endpoints the server doesn't dispatch: {missing}"

    # Every dispatched route must be documented (minus the UI aliases folded
    # into the "/" row).
    undocumented = dispatched - documented - ui_aliases
    assert not undocumented, (
        f"server dispatches endpoints missing from server.ROUTES: {undocumented} "
        "— add them to ROUTES and run python scripts/gen_docs.py"
    )
